accounts/urls.py
from django.urls import path
from .views import register,Login,Logout,profileView


urlpatterns = [
    path('register/',register,name="account-register"),
    path('login/', Login.as_view(),name="account-login"),
    path('logout/',Logout.as_view(),name="account-logout"),
    path('profile/',profileView,name="account-profile"),
]

deeDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('todos.urls')),
    path('accounts/', include('accounts.urls'))
]

todos/urls.py
from django.urls import path
from .views import (testView, isCompleted, AddNewTodo, TodoListView, TodoDetail, AddNewLabel, LabelLists, LabelDetail,
                    TodoUpdateView, TodoDeleteView, LabelLists, LabelUpdateView,LabelDeleteView)

urlpatterns = [
    #
    path('test', testView, name='test'),
    path('', TodoListView.as_view(), name='todos-list'),
    path('todo/new', AddNewTodo.as_view(), name='todos-add'),
    path('todo/<int:pk>', TodoDetail.as_view(), name="todos-detail"),
    path('todo/<int:pk>/update/', TodoUpdateView.as_view(), name="todos-update"),
    path('todo/<int:pk>/delete/', TodoDeleteView.as_view(), name="todos-delete"),
    path('todo/<int:pk>/<int:state>/completed/',isCompleted, name="todos-is-completed"),
    # lablel
    path('label/', LabelLists.as_view(), name="todos-label-list"),
    path('label/new/', AddNewLabel.as_view(), name="todos-label-create"),
    path('label/<int:pk>/', LabelDetail.as_view(), name="todos-label-detail"),
    path('label/<int:pk>/update/', LabelUpdateView.as_view(),name="todos-label-update"),
    path('label/<int:pk>/delete/', LabelDeleteView.as_view(),name="todos-label-delete"),

]
"""
A user should be able to set priority for each TODO

Arrange each TODO by their priority. (Use order_by in Django models)

Identify each user using authentication and authorization: 
"""

accounts/models.py
from django.db import models

# Create your models here.

todos/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Label(models.Model):
    title = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=1)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def get_absolute_url(self):
        return reverse("todos-label-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title


class TodoLevel(models.Model):
    title = models.CharField(max_length=20)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    


class Todo(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    label = models.ForeignKey(Label, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    todo_priority = models.ForeignKey(TodoLevel, on_delete=models.CASCADE, default=1)

    def get_absolute_url(self):
        return reverse("todos-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms  import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('todos-list')

    else:
        form = UserRegisterForm()

    return render(request, 'accounts/reg.html', {'form': form})


class Login(LoginView):
    template_name = "accounts/login.html"

class Logout(LogoutView):
    template_name = "accounts/logout.html"

@login_required
def profileView(request):
    return render(request, 'accounts/profile.html')

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from .models import Label, Todo
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def testView(request):
    form = UserCreationForm
    #template_name = 'test.html'
    return render(request, 'test.html',{'form':form})

# CreateView
class AddNewTodo(LoginRequiredMixin,CreateView):
    model = Todo
    #label = Label.objects.filter(owner=request.user)
    fields = ['title', 'label','todo_priority', 'description']


    def form_valid(self,form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

# #ListView
class TodoListView(LoginRequiredMixin,ListView):
    model = Todo
   
    def get_queryset(self):
        return Todo.objects.filter(owner=self.request.user).order_by('-todo_priority')


# DetailView
class TodoDetail(LoginRequiredMixin,DetailView):
    model = Todo

    def get_queryset(self):
        return Todo.objects.filter(owner=self.request.user)
    

# UpdateView
class TodoUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Todo
    fields = ['title', 'label', 'description']

    def test_func(self):
        todo = self.get_object()
        if todo.owner == self.request.user:
            return True 
        return False

# DeleteView
class TodoDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Todo
    success_url = reverse_lazy('todos-list')

    def test_func(self):
        todo = self.get_object()
        if todo.owner == self.request.user:
            return True 
        return False


# CompletedView

@login_required
def isCompleted(request, pk, state):
    todo = get_object_or_404(Todo, pk=pk)
    if request.user == todo.owner:
        if state == 0:
            # status will be equal to False
            todo.status = False
            todo.save()
        else:
            # status will be equal to True
            todo.status = True
            todo.save()
    else:
        return render(request,'todos/todos_list.html')

    return redirect('todos-detail', pk=pk)

# CreateView
class AddNewLabel(LoginRequiredMixin,CreateView):
    model = Label
    fields = ['title']

    def form_valid(self, form):
        # setting the author of label
        form.instance.owner = self.request.user
        return super().form_valid(form)

# #ListView
class LabelLists(ListView):
    model = Label

    def get_queryset(self):
        return Label.objects.filter(owner=self.request.user)

# #DetailView
class LabelDetail(LoginRequiredMixin,DetailView):
    model = Label

    def get_queryset(self):
        return Label.objects.filter(owner=self.request.user)

# #UpdateView
class LabelUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Label
    fields = ['title']

    def test_func(self):
        label = self.get_object()
        if label.owner == self.request.user:
            return True
        return False

# #DeleteView
class LabelDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Label
    success_url = reverse_lazy('todos-label-list')

    def test_func(self):
        label = self.get_object()

        if label.owner == self.request.user:
            return True 
        return False

templates/accounts/login.html
{% extends 'form.html' %}
{% block submit_button_name %}
        Login
{% endblock submit_button_name %}

templates/accounts/logout.html
{% extends 'base.html' %}
{% block contents %}
<div class="container">
    <h5>You have logged in successfully... Please <a href="{% url 'account-login' %}">Login</a> again to access your Todos</h5>
</div>
{% endblock contents %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% block contents %}

 Welcome <b>{{user.email}}</b> to DeeDo App.
{% endblock contents %}

templates/accounts/reg.html
{% extends 'form.html' %}
{% block submit_button_name %}
        Register
{% endblock submit_button_name %}

templates/base.html
{% load static %}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/todos.html' %}" />
<!------ Include the above in your HEAD tag ---------->

<div class="container" style="margin-top:15px;">

	<div class="row">
        <div class="col-lg-11">
            {% include 'nav.html' %}
            {% comment %} <h3 class="text-center">Basic Example</h3> {% endcomment %}
            <div class="well" style="max-height: 800px; overflow: auto;">
                {% block contents %}
                {% endblock contents %}
            </div>
        </div>
	</div>

</div>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>

templates/form.html
{% extends 'base.html' %}
{% load widget_tweaks %}}
{% block contents %}
    <hr/>
    <form method="POST" novalidate>
        {% csrf_token %}
        {% for field in form %}
                <div class="form-group">
                        {{ field.label_tag }}
                            {% if form.is_bound %}
                                {% if field.errors %}
                                    {% render_field field class="form-control is-invalid" %}
                                    {% for error in field.errors %}
                                        <div class="invalid-feedback"> {{ error }} </div>
                                    {% endfor %}
                                {% else %}
                                {% render_field field class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field field class="form-control" %}
                        {% endif %}
                        
                        {% if field.help_text %}
                            <small class="form-text text-muted">
                            {{ field.help_text }}
                            </small>
                        {% endif %}
                </div>
        {% endfor %}
                <div class="float-right">
                    <button type="submit" class="btn btn-dark">{% block submit_button_name %} {% endblock %}</button>
                </div> 
    </form>
{% endblock contents %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'todos-list' %}">DeeDo App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'todos-list' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item"><a class="nav-link" href="{% url 'todos-label-list' %}">Labels</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'todos-list' %}">Todos</a></li>
          </ul>
    {% else %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="{% url 'account-login' %}">Login</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'account-register' %}">Register</a></li>
        </ul>
    {% endif %}

    {% if user.is_authenticated %}
      <ul class="navbar-nav my-2 my-lg-0">
          <li class="nav-item active dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             {{user.username}}'s Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'todos-label-create' %}">Add Label</a>
              <a class="dropdown-item" href="{% url 'todos-add' %}">Add New Todos</a>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Account Settings</a>
              </div>
          </li> 
         <li class="nav-item ">
              <a class="nav-link" href="{% url 'account-logout' %}">Logout <span class="sr-only">(current)</span></a>
        </li>
    </ul>
    {% endif %}
 
  </div>
</nav>

templates/test.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block contents %}
<hr/>
<form method="POST" novalidate>
{% csrf_token %}
{{form|crispy}}
<button type="submit" class="form-control btn btn-outline-dark">Login </button>
</form>

{% endblock %}

templates/todos/label_confirm_delete.html
{% extends 'base.html' %}

{% block contents %}
   <div class="card p-5">
   Are you sure you want to delete this <b>{{object.title}} </b>
   <form method="post">
    {% csrf_token %}
    <hr/>
    <button type="submit" class="btn btn-danger">Yes, Delete </button>
    <a href="{% url 'todos-label-detail' object.id %}" class="btn btn-outline-secondary"> No, Take me back </a>
   </form>
   </div>

{% endblock contents %}

templates/todos/label_detail.html
{% extends 'base.html' %}

{% block contents %}
  {% if object %}
    <ul class="list-group card">
        <li class="list-group-item">
            <div class="card-header">   
                  <h4> {{object.title}} </h4>
            </div>
            <div class="col_md_2_list card-body">
               <b>No of Todos:</b> {{object.todo_set.count}}
            </div>
            <div class="card-footer">
                <div class="cont_text_date">
                    <p>
                        <span>
                        <b>Created:</b>
                        <span class="badge badge-default">{{object.created_on|timesince}} Ago</span>
                        </span>
                       
                        <span class="float-right">

                            <a href="{% url 'todos-label-update' object.pk %}" class="btn-success btn-sm">Edit</a>
                            <a href="{% url 'todos-label-delete' object.pk %}" class="btn-danger btn-sm">Delete</a>
                            
                        </span>
                    </p>
                    <p >
                       
                    </p>     
                </div>    
        
            </div>
        </li>
    </ul>
{% else %}
    <h5>
        No <b>Todolist</b> Added Yet....
        <a href="{% url 'todos-create-label' %}"> Click me to Add </a> 
        New Label to get Started
    </h5>
{% endif %}
{% endblock contents %}

templates/todos/label_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block contents %}
<hr/>
    <form method="post"  novalidate>
        {% csrf_token %}
            <div class="form-group container">
                {{form|crispy}}
            </div>
            <input type="submit" value="+Save Label" class="btn btn-secondary btn-sm float-right"/>
    </form>
    
{% endblock contents %}

templates/todos/label_list.html
{% extends 'base.html' %}

{% block contents %}
       <div class="mt-5">
        <a href="{% url 'todos-label-create' %}" class="btn btn-outline-dark">
             Create New Label
        </a>
        <hr/>
</div>

    {% if object_list %}
    <div>
            <ul class="list-group checked-list-box">
                {% for label in object_list %}
                  <a href="{% url 'todos-label-detail' label.id %}" class="list-group-item list-group-item-action">
                    <li class="list-group-item" data-checked="true">
                        {{label.title}} 
                        <small class="float-right">
                            <a href="{% url 'todos-list' %}"> Todos:
                                <span class="badge badge-default">{{label.todo_set.count}}</span> 
                            </a>
                            <span>| {{label.updated_on|timesince}}
                        </small>
                    </li>
                    </a>
                {% endfor %}   
            </ul>
        
    {% else %}  
        <h5>
            No <b>Todolist</b> Added Yet....
            <a href="{% url 'todos-label-create' %}"> Click me to Add </a> 
            New Label to get Started
        </h5>
    {% endif %}
{% endblock contents %}

templates/todos/todo_confirm_delete.html
{% extends 'base.html' %}

{% block contents %}
   <div class="card p-5">
   Are you sure you want to delete this <b>{{object.title}} </b>
   <form method="post">
    {% csrf_token %}
    <hr/>
    <button type="submit" class="btn btn-danger">Yes, Delete </button>
    <a href="{% url 'todos-detail' object.id %}" class="btn btn-default"> No, Take me back </a>
   </form>
   </div>

{% endblock contents %}

templates/todos/todo_detail.html
{% extends 'base.html' %}

{% block contents %}
  {% if object %}
    <ul class="list-group card">
        <li class="list-group-item">
            <div class="card-header">   
                  <h4>
                    
                    {% if object.status %}
                     <strike>{{object.title}}</srike> | <span class="badge badge-success">Completed</span>
                    {% else %}
                        
                    {% endif %}
                </h4>
            </div>
            <div class="col_md_2_list card-body">
                <p>{{object.description}}</p>
            </div>
            <div class="card-footer">
                <div class="cont_text_date">
                    <p>
                        <span>
                        <b>Created:</b>
                        <span class="badge badge-default">{{object.created_on|timesince}} Ago</span>  |
                        {{object.label}} 
                        </span>
                       
                        <span class="float-right">

                            <a href="{% url 'todos-update' object.pk %}" class="btn-success btn-sm">Edit</a>
                            <a href="{% url 'todos-delete' object.pk %}" class="btn-danger btn-sm">Delete</a>
                             {% if object.status %}
                                <a href="{% url 'todos-is-completed' object.pk 0 %}" class="btn-info btn-sm">Mark as not Done</a>
                            {% else %}
                                 <a href="{% url 'todos-is-completed' object.pk 1 %}" class="btn-info btn-sm">Mark as  Done</a>
                            {% endif %}
                        </span>
                    </p>
                    <p >
                       
                    </p>     
                </div>    
        
            </div>
        </li>
    </ul>
{% else %}
    <h5>
        No <b>Todolist</b> Added Yet....
        <a href="{% url 'todos-create-label' %}"> Click me to Add </a> 
        New Label to get Started
    </h5>
{% endif %}
{% endblock contents %}

templates/todos/todo_form.html
{% extends 'form.html' %}
{% block submit_button_name %}
        +New Todos
{% endblock submit_button_name %}

templates/todos/todo_list.html
{% extends 'base.html' %}

{% block contents %}
<div class="mt-5">
        <a href="{% url 'todos-add' %}" class="btn btn-outline-dark">
             Create New Todos
        </a>
        <hr/>
</div>
    {% if object_list %}
            <ul class="list-group checked-list-box">
                {% for todo in object_list %}
                    {% if todo.status == False %}
                        <a href="{% url 'todos-detail' todo.id %}" class="list-group-item list-group-item-action">
                            {{todo.title}}
                            {% if todo.todo_priority.id == 4 %}
                                <span class="badge badge-danger">{{todo.todo_priority}}</span>
                            {% elif todo.todo_priority.id == 3 %}
                                <span class="badge badge-warning">{{todo.todo_priority}}</span>
                            {% elif todo.todo_priority.id == 2 %}
                                <span class="badge badge-info">{{todo.todo_priority}}</span>
                            {% else %}
                                <span class="badge badge-secondary">{{todo.todo_priority}}</span>
                            {% endif %}
                                <small class="float-right">
                                <span class="badge badge-default"> {{todo.label}} </span> 
                                <span>| {{todo.updated_on|timesince}}
                                </small>
                        </a>
                        
                    {% endif %}
                {% endfor %}   
                <hr/>
                <div>
                {% for todo in object_list %}
                    {% if todo.status %}
                        <strike class="">
                                <a href="{% url 'todos-detail' todo.id %}" class="list-group-item list-group-item-action list-group-item-light">
                                    {{todo.title}}
                                        <small class="float-right"><span class="badge badge-default"> {{todo.label}} </span> <span>| {{todo.updated_on|timesince}}</small>
                                </a>
                        </strike>
                    {% endif %}
                {% endfor %}   
                </div>
            </ul>
    {% else %}  
        <h5>
            No <b>Todolist</b> Added Yet....
            <a href="{% url 'todos-add' %}"> Click me to Add </a> 
            New Label to get Started
        </h5>
    {% endif %}
{% endblock contents %}